(defun phpdoc ()
  "print-the-php-documentor-block"
  (interactive) 
  (search-backward " function")
  (setq method-name (phpdoc-get-method-description))
  (setq params (phpdoc-get-params))
  (phpdoc-block-position)
  (setq inicio (point))
  (setq init-block-point (point))
  (phpdoc-start-line)
  (phpdoc-new-line method-name)
  (phpdoc-new-line)
  (phpdoc-insert-params params)
  (phpdoc-end-line)
  (indent-region inicio (point))
  (goto-char init-block-point)
  (message "PHPDocumentor block created")
)


(defun php-create-setter ()
  "create-the-setter-for-a-variable"
  (interactive) 
  (search-backward "$")
  (setq method-name (phpdoc-get-method-description))
  (setq params (phpdoc-get-params))
  (phpdoc-block-position)
  (setq inicio (point))
  (setq init-block-point (point))
  (phpdoc-start-line)
  (phpdoc-new-line method-name)
  (phpdoc-new-line)
  (phpdoc-insert-params params)
  (phpdoc-end-line)
  (indent-region inicio (point))
  (goto-char init-block-point)
  (message "PHPDocumentor block created")
)


(defun phpdoc-block-position ()
  (previous-line)(beginning-of-line)(newline)
)

(defun phpdoc-new-line (&optional phpdoc-data)
  (newline)
  (indent-according-to-mode)
  (insert (concat "* " phpdoc-data))
)  

(defun phpdoc-end-line ()
  (newline)
  (indent-according-to-mode)
  (insert "*/")
)

(defun phpdoc-start-line ()
  (indent-according-to-mode)
  (insert "/**")
)

(defun phpdoc-get-method-description ()
  (right-word)
  (search-forward " ")
  (setq init-word (point))
  (right-word)
  (buffer-substring-no-properties init-word (point))
)

(defun phpdoc-get-variable-name ()
  (search-forward " ")
  (setq init-word (point))
  (right-word)
  (buffer-substring-no-properties init-word (point))
)

(defun phpdoc-insert-params (param-list)
  (if (> (length param-list) 0)
  (while param-list
    (phpdoc-new-line (concat "@param " (car param-list)))
    (setq param-list (cdr param-list))
   )
  )
)  

(defun phpdoc-get-params ()
  (search-forward "(")
  (setq init-word (point))
  (search-forward ")")
  (setq params (buffer-substring-no-properties init-word (point)))
  (setq param-list (mapcar
                    (lambda (str) (replace-regexp-in-string "^ +" ""
                                    (replace-regexp-in-string " +$" ""
                                      (replace-regexp-in-string "  +" " " str))))
                    (split-string (replace-regexp-in-string ")" "" params) ","))))
